# Generated by Django 2.2.10 on 2020-02-14 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='task name')),
                ('task_status', models.CharField(choices=[('NEW', 'New'), ('DON', 'Done')], default='NEW', max_length=3, verbose_name='task status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='task due date')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='task description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user name')),
            ],
        ),
    ]
