# Generated by Django 2.2.10 on 2020-02-14 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESToDo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task_status',
            field=models.CharField(choices=[('NEW', 'New'), ('DONE', 'Done')], default='NEW', max_length=4, verbose_name='task status'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
